[project]
name = "drftemplate"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.8",
    "django-apscheduler==0.7.0",
    "django-cors-headers==4.9.0",
    "django-environ>=0.12.0",
    "django-filter==25.2",
    "django-redis==6.0.0",
    "django-simpleui==2025.6.24",
    "djangorestframework==3.16.1",
    "djangorestframework-simplejwt==5.5.1",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
]
