# Generated by Django 4.1.3 on 2022-11-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdemo',
            name='name',
            field=models.CharField(max_length=25, verbose_name='名称'),
        ),
    ]
